{% set version = "2.5.1" %}

package:
  name: bob
  version: {{ version }}

source:
  fn: bob-{{ version }}.zip
  url: https://pypi.io/packages/source/b/bob/bob-{{ version }}.zip
  md5: 7c36dacacaf41fed420d9f148752e855

build:
  number: 0
  skip: true  # [win]
  script: python -B setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - libpng 1.6.22|1.6.24  # [osx]
    - bob.extension ==2.3.3
    - bob.blitz ==2.0.11
    - bob.core ==2.1.6
    - bob.io.base ==2.0.12
    - bob.sp ==2.0.7
    - bob.ap ==2.1.1
    - bob.math ==2.0.6
    - bob.measure ==2.2
    - bob.db.base ==2.1.2
    - bob.io.audio ==2.0.3
    - bob.io.image ==2.2
    - bob.io.video ==2.0.12
    - bob.io.matlab ==2.0.7
    - bob.ip.base ==2.0.13
    - bob.ip.color ==2.0.7
    - bob.ip.draw ==2.0.6
    - bob.ip.gabor ==2.0.7
    - bob.learn.activation ==2.0.7
    - bob.learn.libsvm ==2.0.9
    - bob.learn.linear ==2.0.10
    - bob.learn.mlp ==2.1.3
    - bob.learn.em ==2.0.11
    - bob.learn.boosting ==2.0.10
    - bob.db.iris ==2.0.7
    - bob.db.wine ==2.0.6
    - bob.db.mnist ==2.0.6
    - bob.db.atnt ==2.0.7
    - bob.ip.facedetect ==2.1.0
    - bob.ip.optflow.hornschunck ==2.0.10
    - bob.ip.optflow.liu ==2.0.9
    - bob.ip.flandmark ==2.1.3

  run:
    - python
    - bob.extension ==2.3.3
    - bob.blitz ==2.0.11
    - bob.core ==2.1.6
    - bob.io.base ==2.0.12
    - bob.sp ==2.0.7
    - bob.ap ==2.1.1
    - bob.math ==2.0.6
    - bob.measure ==2.2
    - bob.db.base ==2.1.2
    - bob.io.audio ==2.0.3
    - bob.io.image ==2.2
    - bob.io.video ==2.0.12
    - bob.io.matlab ==2.0.7
    - bob.ip.base ==2.0.13
    - bob.ip.color ==2.0.7
    - bob.ip.draw ==2.0.6
    - bob.ip.gabor ==2.0.7
    - bob.learn.activation ==2.0.7
    - bob.learn.libsvm ==2.0.9
    - bob.learn.linear ==2.0.10
    - bob.learn.mlp ==2.1.3
    - bob.learn.em ==2.0.11
    - bob.learn.boosting ==2.0.10
    - bob.db.iris ==2.0.7
    - bob.db.wine ==2.0.6
    - bob.db.mnist ==2.0.6
    - bob.db.atnt ==2.0.7
    - bob.ip.facedetect ==2.1.0
    - bob.ip.optflow.hornschunck ==2.0.10
    - bob.ip.optflow.liu ==2.0.9
    - bob.ip.flandmark ==2.1.3

test:
  imports:
    - bob
    - bob.script
    - bob.test

  commands:
    - OPENBLAS_NUM_THREADS=1 nosetests -sv bob  # [not osx]
    - CFLAGS="${CFLAGS} -pthread" LDFLAGS="${LDFLAGS} -lpthread" DYLD_FALLBACK_LIBRARY_PATH=$PREFIX/lib nosetests -sv bob # [osx]

  requires:
    - nose
    - cmake
    - pkg-config
    - freetype

about:
  home: https://www.idiap.ch/software/bob/
  license: Modified BSD License (3-clause)
  summary: Bob is a free signal-processing and machine learning toolbox originally developed by the Biometrics group at Idiap Research Institute, in Switzerland.

extra:
  recipe-maintainers:
    - 183amir
