travis:
  secure:
    BINSTAR_TOKEN: qSimePapKWYsEjpKlCMYfdeSbnG47CnqMNrlULHGAShSlrnVt/v2AHrhCyntIIIQ39/JbUQ2IGPQX9XndKFJuF3f5QpuxARA/gwZaqbWwtKhgfSRmLvxlHfdIyankxweA0B2YSAglwVAkuYmuvdvgC2n+I3tXnDrX5j8YSexHNH0Iajdg3MbzaoAxNmFLJZjSMtIs/AGfVsw+vx4yVc5XT2IfSmU+oTnn79g4mtaCTqicyOrvAKvTqY8Us4fo6GsAdki/Bp2lXxiviuFXzLdppk0s1uAXI/LVHpaS+/y8kIMogl6jLm+OTw+zcxlZp+/hdefOH7AKoy4fqFbDWvXRAbuHKb3DqPiZ7ypH6fNq/R61RZXtk+JUkrtR4ijm8ooZhIbWtVpoR5p7fp/GYxGQbz95Tj1PDxIDfXUZJLvllfKl7si08nXsFBavMCn6qtO9Us8yddXjrgcAnkOXAFTWfyLg62ujRqEJQwAA2j86pOQNg5VKvbOccON9amlPvc4bktCEcof6CV6w7QaEULTTirDjsKvEHGvlvmLVCNrs1mTdV79mXbTpdiIcGYUsSfysRgxjwcLCxxt3uDJG59mCaYZOYmTIc42s1Hf4+NkqHWoi6DFdAvYgjwwJxOUvYuxRybH+ingeaPsxG0cKZMNmRficJY1yZssmq0sOLcJrF0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
